// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using System.Text;

namespace CodeOfChaos.CliArgsParser.Generators.Helpers;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public class GeneratorStringBuilder{
    private readonly StringBuilder _stringBuilder = new();
    private int _indent;
    private int IndentAmount {
        get => _indent;
        set => _indent = value <= 0 ? 0 : value;
    }

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    #region Append methods(stringbuilder + indent)
    public GeneratorStringBuilder Append(string text) {
        _stringBuilder.AppendWithIndentation(IndentAmount, text);
        return this;
    }
    
    public GeneratorStringBuilder AppendLine(string text) {
        _stringBuilder.AppendLineWithIndentation(IndentAmount, text);
        return this;
    }
    #endregion
    #region Indent methods
    public GeneratorStringBuilder UnIndent() {
        IndentAmount--;
        return this;
    }

    public GeneratorStringBuilder Indent() {
        IndentAmount++;
        return this;
    }
    
    public GeneratorStringBuilder UnIndentLine(string text) {
        _stringBuilder.AppendLineWithIndentation(--IndentAmount, text);
        return this;
    }
    
    public GeneratorStringBuilder IndentLine() {
        _stringBuilder.AppendLineWithIndentation(++IndentAmount);
        return this;
    }
    
    public GeneratorStringBuilder IndentLine(string text) {
        _stringBuilder.AppendLineWithIndentation(++IndentAmount, text);
        return this;
    }
    #endregion
    
    public GeneratorStringBuilder AppendUsings(params string[] usings) {
        foreach (string @using in usings) {
            AppendLine($"using {@using};");
        }
        return this;
    }

    public GeneratorStringBuilder AppendAutoGenerated() {
        return AppendLine("// <auto-generated />");
    }
    
    public override string ToString() => _stringBuilder.ToString();
    public string ToStringAndClear() {
        string result = ToString();
        Clear();
        return result;
    }

    public GeneratorStringBuilder Clear() {
        _stringBuilder.Clear();
        IndentAmount = 0;
        return this;
    }
}
