// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace CodeOfChaos.CliArgsParser.Generators.Helpers;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class GeneratorStringBuilderExtensions {
    public static IGeneratorStringBuilder AppendUsings(this IGeneratorStringBuilder builder, params string[] usings) {
        foreach (string @using in usings) {
            builder.AppendLine($"using {@using};");
        }
        return builder;
    }

    public static IGeneratorStringBuilder AppendAutoGenerated(this IGeneratorStringBuilder builder) {
        return builder.AppendLine("// <auto-generated />");
    }
}