name: Publish Packages

on:
  push:
    tags:
      - 'v*.*.*' # Match version tags like v1.0.0

jobs:
  publish:
    
    runs-on: ubuntu-latest
    
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore CodeOfChaos.CliArgsParser.sln

      - name: Build
        run: dotnet build CodeOfChaos.CliArgsParser.sln --configuration Release --no-restore
          
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |          
          dotnet nuget push src/CodeOfChaos.CliArgsParser.Contracts/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push src/CodeOfChaos.CliArgsParser/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push src/CodeOfChaos.CliArgsParser.Library/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate